TARGET_ARCH_VARIANT := x86
TARGET_HAS_THIRD_PARTY_APPS := true
TARGET_CPU_SMP := true
BOARD_GPU_DRIVERS := nouveau
BOARD_USES_DRM := true
BOARD_HAVE_BLUETOOTH := false
BOARD_WPA_SUPPLICANT_DRIVER := WEXT
WPA_SUPPLICANT_VERSION := VER_0_6_X
BOARD_WPA_SUPPLICANT_PRIVATE_LIB :=
BOARD_USES_ALSA_AUDIO := true
BUILD_WITH_MPLAYER := true
BUILD_EMULATOR_CAMERA_HAL := false
BUILD_EMULATOR_SENSORS_MODULE := false

INTERNAL_USERIMAGES_USE_EXT := false


include $(GENERIC_X86_CONFIG_MK)
