LOCAL_PATH := $(call my-dir)
LOCAL_FIRMWARES := 
TARGET_INITRD_SCRIPTS := $(LOCAL_PATH)/greatzc_e350_info
TARGET_KERNEL_CONFIG := $(LOCAL_PATH)/greatzc_e350_defconfig

include $(GENERIC_X86_ANDROID_MK)
