TARGET_ARCH_VARIANT := x86-e350
TARGET_HAS_THIRD_PARTY_APPS := true
BOARD_GPU_DRIVERS := r600g
BOARD_HAVE_BLUETOOTH := false
BOARD_WPA_SUPPLICANT_DRIVER :=
WPA_SUPPLICANT_VERSION := VER_0_6_X
BOARD_WPA_SUPPLICANT_PRIVATE_LIB :=

include $(GENERIC_X86_CONFIG_MK)
